sudo: required

services:
  - docker

env:
  global:
    - VERSION=7.3.1
    - DOCKER_LOGIN=crazymax
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=linguist
    - QUAY_LOGIN=crazymax
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=linguist
    - secure: gLPLY5cm6J1eWgwm3Rojq3+kAkDTx7BWIFu0E8rLSbPxrFaNXMpfGmuzyVS94i2YJs2uyLBdv+S84CsgF5IQTbQyS0Qlg6VnmGloJQNSG+V1pPvoaSnZVJY6nemtTixXkhLLIqUxwSPmFYLAWIGD5ydKs292fSBYyvzHMtfUBGZjYMcCmrj3J+0hluUsiRsHYf/iBwXX+kEb2tkxva/OI5zIxO0wwSu9xr9pfepINWLx2lmU7arGPBvRo5V2b0KUMJKoTp+Gih4B6s1W+K/x5GI8HEEQsZCYGXJUn++UQmCzjdSfTAztWPJscAkEsAyqnBmpaMvwIAz52Ir9XUcdGi9XFKDYjCY/nJXu4K9PfynHCc6v2XhZ1Qeqd8BL4DTuxVO2N0WKsjcr0P/8nxJItjo0JVDLy8WzoMzamPExHeKt+hpAmK/hA/MDmHG05f07GfsPqZrd5dIwjxgywMYBjQDaeOVDj/orm32Mfyr4/dGxCJQ49cGRek9LZyZpKYTixuh102AcgAd0H+SuO8TUcO9iWVAUxhbmB5ajQ8nuyKfUqHTF1PbuvcPlyA0c4UVDORfkN6Pr/F40KMXCtqX6c6kERq42bd3w70Pibr4Wf+P4GqFKEIL6+QCpsE4ROpdeOlF06PP51qb3NzwriO8YgIGylHG13571lVKkQzjpOyw= # DOCKER_PASSWORD
    - secure: vSwiI/VYm+uPcqJg5cYwEiC2Tb3lAUqz4LSa7X7ZcAy0ZXs0hf9EtBtiDL1D8kxZbL46M08SrLIzCfIsN6rukUarpe3FEnRSWws0bUTIAbnZ7Ha6uMffihGwLmFlVhbXomVb7iZ8wRlLckno0aPJ9qmCAmn86wimoRFDhqS1TvDbjE88JRwYkmCD5s7yhgB0dPsW8Lw9gCXoMZzZ4dPaX5TasT+RtAs+2cw7t8S3MEdkQTp6vyILclcHUybBMuD5qyJW2KaNLKMYxTUWolVutDOAQ9b0+clj/o2ig5nfdy279p77yDwQR0BnJcMYJ/ITxHvgxSDKc3M5h9dyRoXS9xX2lMLn4UtjjbNgfRvfyUd3jzOkKtUADqV2YXAhbIxYTl9dG/1oUI+itW2QvGVdQbSehChV73fDuaPdfC4VXMKj8sprY2w2Mh9OOdYuS+bUsx1axxbb5uwQohTD1yPd5GfIUgRzkmYDcUDx0mEFdAbIzPe3xmTjfdXqLoju04AcuyUVtumNrp2IVmEF+Xw7wajqv4mObTnwjOMMf1p4j9nq7bq7yCgkgUMoGqCSp8hrU4KkTYwE6wors3RaYXpXLjtEsp7O0E1o5IVvbBnUs8P7k5npP3cPKFmrZeuO+5p5ik9VhPw+nauyZfaT2HNMjSZx6CHfpb7/sNM0mQQFrw8= # QUAY_PASSWORD

before_install:
  - sudo apt-get update
  - docker --version

script: ./build.sh

notifications:
  email:
    recipients:
      - travisci@crazymax.dev
    on_success: always
    on_failure: always
