name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    uses: docker/github-builder/.github/workflows/bake.yml@2497a7d1e7d8683af4949c9d6d62012bc16ed59c # v1.5.0
    permissions:
      contents: read # same as global permissions
      id-token: write # for signing attestation(s) with GitHub OIDC Token
      packages: write # required to push to GHCR
    with:
      setup-qemu: true
      target: image-all
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      set-meta-labels: true
      meta-images: |
        crazymax/linguist
        ghcr.io/crazy-max/linguist
      meta-tags: |
        type=match,pattern=(.*)-r,group=1
        type=ref,event=pr
        type=edge
      meta-labels: |
        org.opencontainers.image.title=Linguist
        org.opencontainers.image.description=GitHub Language Savant to detect blob languages
        org.opencontainers.image.vendor=CrazyMax
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        - registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
